function plot_route( self )
% profil.plot_route

% $Id: plot_route.m 261 2013-08-16 15:29:37Z jgrelet $

% choix  : 0 -> choix multiples
%          1 -> choix exclusif (uibunttongroup)

% a modifier, pour test actuellement
 netcdfFile = 0;

root       = get(0, 'UserData' );

choix      = get( findobj( 'Tag', 'levitus' ), 'Value' );
% rajoute pour initialisation de plot_route avec type_trace = section
if root.type_trace_value == 2   % section
  choix = 2;
end  

% appel de plot_route oceano
hdl_figure = plot_route(super(self));
set(hdl_figure,...
  'name', sprintf('Profil: %s',get( data_0d(self), 'CYCLE_MESURE')),...
  'HandleVisibility','on',...
  'numbertitle', 'off',...
  'MenuBar','figure');

% supprime le double handle, pb d'heritage pas tres clair
hdl_type_trace = findobj( 'Tag', 'type_trace' );
if( isempty(hdl_type_trace) )
  % handle du panel pour le choix du trac� (profil ou section)
  hdl_type_trace = uipanel('Title','Trace',...
    'Tag','type_trace',...
    'FontSize',8,...
    'Units','pixels',...
    'Position',[595 695 100 50]);

  uicontrol('Style','popupmenu',...
    'parent',hdl_type_trace,...
    'String',root.type_trace,...
    'Tag','popup_type_trace',...
    'Value', root.type_trace_value,...
    'pos',[10 10 85 20],...
    'BackgroundColor','w',...
    'Callback', 'select_type_trace_callback' );
else
  %figure(hdl_type_trace);
end

% premier passage
if isempty(choix)
  choix = 0;
  % Radio button pour choix levitus
  hdl_levitus = uipanel('Title','Climatology',...
    'FontSize',8,...
    'Units','pixels',...
    'Position',[595 650 100 50]);
  uicontrol('Style','Radio',...
    'parent',hdl_levitus,...
    'String','WOA01',...
    'Tag','Climatology',...
    'Value', choix,...
    'pos',[10 10 85 20],...
    'HandleVisibility','on',...
    'Callback', 'getChoixLevitusCallback' );
end

% edit des profils si travail sur fichier netcdf
if netcdfFile == 1
  % Radio button pour choix levitus
  hdl_levitus = uipanel('Title','Edit',...
    'FontSize',8,...
    'Units','pixels',...
    'Position',[595 595 100 50]);
  uicontrol('Style','Radio',...
    'parent',hdl_levitus,...
    'String','Edit',...
    'Tag','edit',...
    'Value', choix,...
    'pos',[10 10 85 20],...
    'HandleVisibility','on',...
    'Callback', 'getEditCallback' );
end

% recupere la liste des parametres (cles)
cles    = keys( get( self, 'data_2d' ) );

% Radio buttons pour choix parametres GF3 (ROSCOP)
choix_parametres( hdl_figure, cles, choix );
