function datagui
%%
% dataGUI.m
% Interface graphique des traces de donnees Oceanographiques
%
% La structure root contient le parametrage de l'interface
% est sauvegardee dans le champ UserData de la figure racine 0

% $Id: datagui.m 190 2013-01-21 10:06:29Z jgrelet $

%% TIPS:
% faire un clear classes apres avoir modifie la structure d'un objet

% Pour regenerer un fichier de config datagui.mat, changer le numero 
% de version, ex '0.30g' -> '0.30h'
% Location de datagui.mat:
%
% Windows XP:   %appdata%\MathWorks\MATLAB\<realease Matlab>
%               %appdata%\MathWorks\MATLAB\R14SP3
% Linux/Unix:   ~/.matlab

%% COPYRIGHT & LICENSE
% Copyright 2007 Jacques Grelet - IRD, all rights reserved.
%
% This file is part of Datagui.
%
%    Datagui is free software; you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation; either version 2 of the License, or
%    (at your option) any later version.
%
%    Datagui is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with Datagui; if not, write to the Free Software
%    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

%% PROGRAM BEGIN
clear all;
 
addpathdef_datagui;

%% VERSION
VERSION = '0.47';  % 0.47 avril 2014   PIRATA-FR24
                   % add Netcdf OceanSITES
                   % 0.46 juillet 2012 Pandora


%% INIT
% file_name, retourne le nom du script: datagui
% mfilename;

root = init_config( mfilename, VERSION );

%% MAIN FIGURE
% creation fenetre generale
main_fig = figure( ...
           'Position',[10 10 300 440],...
           'Name','DataGUI - Main',...
           'numbertitle', 'off', ...
           'Tag','main',...
           'MenuBar','none',...
           'HandleVisibility','on',...
           'NextPlot','new',...
           'CloseRequestFcn', 'datagui_closereq_callback',...
           'Color', get( 0, 'DefaultUIControlBackgroundColor' ));        

% constructeur d'un objet de type trajectoire par defaut
% self = trajectoire('sst'); 
% sauvegarde de l'objet, il faut utiliser builtin
builtin( 'set', main_fig, 'UserData', root );   

%creation du texte "nom de fichier"
uicontrol( 'Style','text',...
           'Position', [20 410 290 20],...
           'ForegroundColor','r',...
           'String',['Pick one file: ' root.path] ,...
           'Tag','text_file',...
           'HorizontalAlignment','left');

% creation popup "nom de fichier" et appel read_file
uicontrol( 'Style','popupmenu',...
           'Position',[20 380 150 30],...
           'String',root.files,...
           'Value', root.files_value,...
           'Tag','popup_file',...
           'BackgroundColor','w',...
           'Callback','select_file_callback');

% pushbutton getting uigetfile
uicontrol( 'Style','pushbutton',...
           'Position',[190 388 100 23],...
           'String','Change directory',...
           'Tag','button_getfile', ...
           'CallBack','change_directory_callback');
 
% select type file (DataGUI/XML/NetCDF/ASCII/Excel)
% definit dans common/select_type.m
uicontrol( ...
           'Style','text',...
           'Position',[20 360 150 20],...
           'ForegroundColor','b',...
           'String','Select format',...
           'HorizontalAlignment','left');         
uicontrol( ...
           'Style','popupmenu',...
           'Position',[20 340 150 20],...
           'String',root.format,...
           'BackgroundColor','w',...
           'Value',root.format_value,...
           'Tag', 'popup_format', ...
           'CallBack', 'select_format_callback');
           
% select data type 'TIME SERIE','TSG','METEO','BATHYMETRIE,'RADIO SONDAGE',...
%                  'ADCP','CTD','XBT','BOUTEILLES''
uicontrol( 'Style','text',...
           'Position', [20 310 150 20],...
           'ForegroundColor','k',...
           'String','Select data type ',...
           'HorizontalAlignment','left');
                          
uicontrol( 'Style','popupmenu',...
           'Position',[20 280 150 30],...
           'String',root.type,...
           'Value', root.type_value,...
           'Tag','popup_type',...
           'BackgroundColor','w',...
           'Callback','select_type_callback');   
                          
% select X axis
uicontrol( 'Style','text',...
           'Position', [20 260 150 20],...
           'ForegroundColor','k',...
           'String','Set plot axis',...
           'HorizontalAlignment','left');
                          
uicontrol( 'Style','popupmenu',...
           'Position',[20 230 150 30],...
           'String','DAYS|LATX|LONX',...
           'Value',root.axis_value,...
           'Tag','popup_axis',...
           'BackgroundColor','w',...
           'Callback','select_axis_callback');  
                          
% select route axis
uicontrol( 'Style','text',...
           'Position', [20 210 150 20],...
           'ForegroundColor','k',...
           'String','Set route axis',...
           'HorizontalAlignment','left');
         
uicontrol( 'Style','popupmenu',...
           'Position',[20 180 150 30],...
           'String',root.route,...
           'Value', root.route_value,...
           'Tag','popup_route',...
           'BackgroundColor','w',...
           'Callback','select_route_callback');  

% select map
uicontrol( 'Style','text',...
           'Position', [20 160 150 20],...
           'ForegroundColor','k',...
           'String','Select map',...
           'HorizontalAlignment','left');
         
uicontrol( 'Style','popupmenu',...
           'Position',[20 130 150 30],...
           'String',root.map,...
           'Value', root.map_value,...
           'Tag','popup_map',...
           'BackgroundColor','w',...
           'Callback','select_map_callback');                            
 
                     
                            
% The quit button
uicontrol( 'Style','pushbutton',...
           'Position',[20 20 150 30],...
           'String','Quit',...
           'Interruptible','off',...
           'BusyAction','cancel',...
           'Tag','button_quit',...
           'Callback', 'button_quit_callback');

% set(main_fig,'HandleVisibility','callback');
set(main_fig,'HandleVisibility','callback');

%% PLOT_ROUTE
% si instance self non nulle et en memoire, on trace la route
plot_route;


%% CLEAR VARIABLES
clear main_fig VERSION
% end datagui
