# this is a configuration file for cruiseTrack2kml program

cruise = "PIRATA-FR26"
ship = "THALASSA"

#ctd_plots = "http://192.168.51.167/ctd-plots/downcast/dfr26%s.jpg"
ctd_plots = "http://www.brest.ird.fr/us191/cruises/pirata-fr26/dfr26%s.jpg"
ctd_prefix = 3
#tsg_plots = "http://192.168.51.167/tsg-plots/PIRATA-FR26_TSG_SCATTER.png"
tsg_plots = "http://www.brest.ird.fr/us191/cruises/pirata-fr26/PIRATA-FR26_TSG_SCATTER.png"

size_plots = 700
station_number = true
tsg_skip = 2
tsg_split = "LATITUDE,2,LONGITUDE,3"
ctd_skip = 1
ctd_split = "PRFL,1,BEGIN_DATE,2,BEGIN_TIME,3,END_DATE,4,END_TIME,5,LAT,6,LAT_S,7,LON,8,LON_S,9,TYPE_CAST,-1,PMAX,10,BOTTOM_DEPTH,11"

[windows]
tsg_file = "../../THERMO/ascii/pirata-fr26.gps"
ctd_file = "../ascii/pirata-fr26.ctd"
kml_file = "pirata-fr26.kml"

[unix]
tsg_file = "./data/fr26/ascii/pirata-fr26.gps"
ctd_file = "./data/fr26/pirata-fr26.ctd"
kml_file = "./pirata-fr26.kml"
