function QC_selected = define_QC()
%
% Fonction inutil maintenant : L'utilisateur ne doit pas avoir à choisir
% directement un code qualité. Le CQ doit etre mis en place automatiquement
% par l'intermediaire des fonctions proposées dans le ui_panel hdl_action. 
% Tous les points non modifié devront alors recevoir un code qualité à 1. 
% Les autres recevront un code qualité associé au type d'action effectué
% sur ce point. 


if isempty(findobj('Tag','tag_QC'))

  figure( 'Position',[10 10 300 440],...
    'Name','Definir un code qualite',...
    'numbertitle', 'off', ...
    'Tag','tag_QC',...
    'MenuBar','none',...
    'HandleVisibility','on',...
    'Color', get( 0, 'DefaultUIControlBackgroundColor' ));

  hdl_qualite = uipanel('parent',findobj('Tag','tag_QC'),...
    'Title','Code Qualite',...
    'tag','tag_QC_panel',...
    'FontSize',8,...
    'Units','pixels',...
    'Position',[10 60 280 350]);

  h = uibuttongroup('parent' ,findobj('Tag','tag_QC_panel'),...
    'Title', 'CQ Possibles', 'visible','off','Position',[0.086 0.15 .85 0.8]);
  uicontrol('Style','Radio', 'String', '0 : Aucun CQ attribué',...
    'pos',[10 220 200 20],'parent',h,'Tag', '0','HandleVisibility','off');
  uicontrol('Style','Radio', 'String', '1 : Surment correct',...
    'pos',[10 170 200 20],'parent',h,'Tag', '1','HandleVisibility','off');
  uicontrol('Style','Radio', 'String', '2 : Probablement bon',...
    'pos',[10 120 200 20],'parent',h,'Tag', '2','HandleVisibility','off');
  uicontrol('Style','Radio', 'String', '3 : Probablement faux',...
    'pos',[10  70 200 20],'parent',h,'Tag', '3','HandleVisibility','off');
  uicontrol('Style','Radio', 'String', '4 : Surment erroné',...
    'pos',[10  20 200 20],'parent',h,'Tag', '4','HandleVisibility','off');
  set(h,'SelectedObject',findobj('Tag', '0'));
  set(h,'Visible','on');

  uicontrol('parent',findobj('Tag','tag_QC'),...
    'String','Valider',...
    'Style', 'pushbutton',...
    'FontSize',8,...
    'Units','pixels',...
    'Position',[100 70 100 30],...
    'Callback', @valid_callback_CQ);
end

uiwait
QC_selected = get(get(h, 'SelectedObject'),'Tag');
close(findobj('Tag','tag_QC'));
end

function valid_callback_CQ(obj, eventdata)
uiresume
end

