function plot_route( self )
% profil.plot_route

% $Id: plot_route.m 92 2006-08-01 12:40:55Z nvuillau $

root       = get(0, 'UserData' );
markersize = root.markersize;
choix      = get( findobj( 'Tag', 'WOA01' ), 'Value' );

% appel de plot_route oceano
hdl_figure = plot_route(super(self));

% premier passage
if isempty(choix)
  choix = 0;
  % Radio button pour choix levitus
  hdl_levitus = uipanel('Title','Climatology',...
    'FontSize',8,...
    'Units','pixels',...
    'Position',[595 650 100 50]);
  uicontrol('Style','Radio',...
    'parent',hdl_levitus,...
    'String','WOA01',...
    'Tag','levitus',...
    'Value', choix,...
    'pos',[10 10 85 20],...
    'HandleVisibility','on',...
    'Callback', 'getChoixLevitusCallback' );
end

hdl_traj_color = uipanel('Title', 'Traj. Color',...
    'FontSize', 8,...
    'Units', 'pixels',...
    'Position', [595 600 100 50]);
uicontrol('Style', 'Radio',...
    'parent', hdl_traj_color,...
    'String', 'Traj. Color',...
    'Tag', 'Tag_trajcol',...
    'Value', 0,...
    'Pos',[10 10 85 20],...
    'HandleVisibility','on',...
    'Callback','getRadioParamCallback');

cles    = keys( get( self, 'data_2d' ) );

% Radio buttons pour choix parametres GF3 (ROSCOP)
choix_parametres( hdl_figure, cles, choix );
